language: node_js
node_js:
- '10'
- '12'
addons:
  code_climate:
    repo_token: "$CODE_CLIMATE_TOKEN"
install:
- npm install --loglevel=error
- npm install --loglevel=error -g mocha greenkeeper-lockfile@1
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
before_script:
- npm --silent run-script eslint
- ./cc-test-reporter before-build
- greenkeeper-lockfile-update
after_script:
- ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
- greenkeeper-lockfile-upload
jobs:
  include:
  - stage: npm release
    if: tag IS present
    script: skip
    deploy:
      provider: npm
      email: "$NPM_EMAIL"
      api_key: "$NPM_API_KEY"
      on:
        tags: true
        repo: eexit/ghost-storage-cloudinary
