language: node_js
node_js:
  - "8"
  - "6"
addons:
  code_climate:
    repo_token: $CODE_CLIMATE_TOKEN
branches:
  only:
  - master
  - /^[0-9]+(\.[0-9]+)*((-staging|-beta|-alpha|-test)[0-9]*)?$/
  - /^greenkeeper/.*$/
install:
  - npm install --loglevel=error
  - npm install --loglevel=error -g mocha greenkeeper-lockfile@1
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
before_script:
  - npm --silent run-script eslint
  - ./cc-test-reporter before-build
  - greenkeeper-lockfile-update
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  - greenkeeper-lockfile-upload
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  on:
    tags: true
